### 注册配置
POST http://localhost:9001/configs
Content-Type: application/json

{
  "app": "demo-consumer",
  "env": "dev",
  "ns": "public",
  "pkey": "ccrpc.consumer.faultLimit",
  "pval": "6"
}

###
GET http://localhost:9000/configs?app=demo-consumer&env=dev&ns=public

###
GET http://localhost:9001/configs?app=demo-consumer&env=dev&ns=public

###
GET http://localhost:9002/configs?app=demo-consumer&env=dev&ns=public

###
GET http://localhost:9000/version?app=application&env=dev&ns=public